const deptMapping = [
    {
        "Code": "013",
        "Long": "School of Chemical Engineering",
        "Short": "Chemical Engineering",
        "Subject": 'CENG',
    },
    {
        "Code": "014",
        "Long": "School of Chemistry",
        "Short": "Chemistry",
        "Subject": 'CHEM',
    },
    {
        "Code": "015",
        "Long": "Civil Engineering",
        "Short": "Civil Engineering",
        "Subject": 'CIVI',
    },
    {
        "Code": "016",
        "Long": "School of Computer Science",
        "Short": "Computer Science",
        "Subject": 'COMP',
    },
    {
        "Code": "018",
        "Long": "School of Dentistry",
        "Short": "Dentistry",
        "Subject": 'DENT',
    },
    {
        "Code": "019",
        "Long": "Earth and Environmental Sciences",
        "Short": "Earth and Environ Sciences",
        "Subject": 'EART',
    },
    {
        "Code": "020",
        "Long": "School of Education",
        "Short": "School of Education",
        "Subject": 'EDUC',
    },
    {
        "Code": "021",
        "Long": "Electronic, Electrical and Systems Engineering",
        "Short": "Elec, Elec & Sys Engineering",
        "Subject": 'ELEC',
    },
    {
        "Code": "022",
        "Long": "Geography",
        "Short": "Geography",
        "Subject": 'GEOG',
    },
    {
        "Code": "023",
        "Long": "School of Nursing",
        "Short": "Nursing",
        "Subject": '',
    },
    {
        "Code": "023",
        "Long": "School of Nursing and Midwifery",
        "Short": "Nursing and Midwifery",
        "Subject": '',
    },
    {
        "Code": "027",
        "Long": "Birmingham Law School",
        "Short": "Law",
        "Subject": 'LAWS',
    },
    {
        "Code": "028",
        "Long": "Mechanical Engineering",
        "Short": "Mechanical Engineering",
        "Subject": 'MECH',
    },
    {
        "Code": "029",
        "Long": "School of Mathematics",
        "Short": "Mathematics",
        "Subject": 'MATH',
    },
    {
        "Code": "031",
        "Long": "School of Metallurgy and Materials",
        "Short": "Metallurgy & Materials",
        "Subject": 'MATR',
    },
    {
        "Code": "032",
        "Long": "School of Physics and Astronomy",
        "Short": "Physics & Astronomy",
        "Subject": 'PHYS',
    },
    {
        "Code": "033",
        "Long": "School of Psychology",
        "Short": "School of Psychology",
        "Subject": 'PSYC',
    },
    {
        "Code": "036",
        "Long": "School of Sport, Exercise and Rehabilitation Sciences",
        "Short": "Sport, Ex and Rehab Sciences",
        "Subject": 'SPEX',
    },
    {
        "Code": "038",
        "Long": "School of Biosciences",
        "Short": "School of Biosciences",
        "Subject": 'BIOS',
    },
    {
        "Code": "039",
        "Long": "Centre for Learning and Academic Development",
        "Short": "Centre for Learning & Acad Dev",
        "Subject": '',
    },
    {
        "Code": "106",
        "Long": "Institute of Cardiovascular Sciences",
        "Short": "Inst of Card Sciences",
        "Subject": '',
    },
    {
        "Code": "108",
        "Long": "African Studies and Anthropology",
        "Short": "African Studies & Anthropology",
        "Subject": 'AFST',
    },
    {
        "Code": "113",
        "Long": "International Development",
        "Short": "International Development",
        "Subject": 'IDEV',
    },
    {
        "Code": "113",
        "Long": "Public Administration and Policy",
        "Short": "Public Administration and Policy",
        "Subject": 'IDEV',
    },
    {
        "Code": "114",
        "Long": "Drama and Theatre Arts",
        "Short": "Drama and Theatre Arts",
        "Subject": 'DRMA',
    },
    {
        "Code": "115",
        "Long": "Economics",
        "Short": "Economics",
        "Subject": 'ECON',
    },
    {
        "Code": "122",
        "Long": "Health Services Management Centre",
        "Short": "Health Services Management Cen",
        "Subject": 'HSMN',
    },
    {
        "Code": "124",
        "Long": "Department of Art History, Curating and Visual Studies",
        "Short": "Art Hist, Cur and Vis Studies",
        "Subject": 'AHCV',
    },
    {
        "Code": "128",
        "Long": "Institute of Cancer and Genomic Sciences",
        "Short": "Inst of Cancer / Genomic Sci",
        "Subject": '',
    },
    {
        "Code": "131",
        "Long": "Institute of Local Government Studies",
        "Short": "Inst Local Government Studies",
        "Subject": 'PUBL',
    },
    {
        "Code": "134",
        "Long": "Music",
        "Short": "Music",
        "Subject": 'MUSI',
    },
    {
        "Code": "140",
        "Long": "Philosophy",
        "Short": "Philosophy",
        "Subject": 'PHIL',
    },
    {
        "Code": "142",
        "Long": "Political Science and International Studies",
        "Short": "Political Sci & Intern'tl Stud",
        "Subject": 'POLS',
    },
    {
        "Code": "150",
        "Long": "Theology and Religion",
        "Short": "Theology and Religion",
        "Subject": 'THEO',
    },
    {
        "Code": "153",
        "Long": "Languages for All",
        "Short": "Languages for All",
        "Subject": 'LANG',
    },
    {
        "Code": "171",
        "Long": "Shakespeare Institute",
        "Short": "Shakespeare Institute",
        "Subject": 'ENGL',
    },
    {
        "Code": "173",
        "Long": "Institute of Immunology and Immunotherapy",
        "Short": "Inst of Immunol + Immunoth",
        "Subject": '',
    },
    {
        "Code": "173",
        "Long": "Immunology and Immunotherapy",
        "Short": "Inst of Immunol + Immunoth",
        "Subject": '',
    },
    {
        "Code": "182",
        "Long": "Personal Skills Award",
        "Short": "PSA",
        "Subject": '',
    },
    {
        "Code": "184",
        "Long": "LES - College Hub",
        "Short": "LES - College Hub",
        "Subject": '',
    },
    {
        "Code": "188",
        "Long": "Ironbridge International Institute for Cultural Heritage",
        "Short": "Ironbridge Int Inst & Cul Her",
        "Subject": 'HIST',
    },
    {
        "Code": "193",
        "Long": "CAL - College Hub",
        "Short": "CAL - College Hub",
        "Subject": '',
    },
    {
        "Code": "197",
        "Long": "Marketing",
        "Short": "Marketing",
        "Subject": 'MRKT',
    },
    {
        "Code": "200",
        "Long": "COS - College Hub",
        "Short": "COS - College Hub",
        "Subject": 'SSCI',
    },
    {
        "Code": "202",
        "Long": "EPS - College Hub",
        "Short": "EPS - College Hub",
        "Subject": '',
    },
    {
        "Code": "204",
        "Long": "School of Biomedical Sciences",
        "Short": "Biomedical Sciences",
        "Subject": '',
    },
    {
        "Code": "205",
        "Long": "School of Pharmacy",
        "Short": "Pharmacy",
        "Subject": 'PHAR',
    },
    {
        "Code": "207",
        "Long": "MDS - College Hub",
        "Short": "MDS - College Hub",
        "Subject": '',
    },
    {
        "Code": "208",
        "Long": "English, Drama and Creative Studies",
        "Short": "Eng, Drama, Creative Studies",
        "Subject": 'ENGL',
    },
    {
        "Code": "210",
        "Long": "Languages, Cultures, Art History and Music",
        "Short": "Lang, Cult, Art Hist and Music",
        "Subject": '',
    },
    {
        "Code": "211",
        "Long": "Birmingham Business School",
        "Short": "Birmingham Business School",
        "Subject": 'BUSI',
    },
    {
        "Code": "212",
        "Long": "Government",
        "Short": "Government",
        "Subject": '',
    },
    {
        "Code": "213",
        "Long": "Philosophy, Theology and Religion",
        "Short": "Phil, Theol & Religion",
        "Subject": '',
    },
    {
        "Code": "214",
        "Long": "Birmingham International Academy",
        "Short": "Birmingham International Acad",
        "Subject": 'LANG',
    },
    {
        "Code": "215",
        "Long": "Birmingham Medical School",
        "Short": "Birmingham Medical School",
        "Subject": '',
    },
    {
        "Code": "216",
        "Long": "Institute of Applied Health Research",
        "Short": "Inst of Applied Health Res",
        "Subject": '',
    },
    {
        "Code": "216",
        "Long": "Department of Applied Health Research",
        "Short": "Inst of Applied Health Res",
        "Subject": '',
    },
    {
        "Code": "217",
        "Long": "Birmingham Clinical Trials Unit (BCTU)",
        "Short": "Bhm Clinical Trial Unit (BCTU)",
        "Subject": '',
    },
    {
        "Code": "218",
        "Long": "Cancer Clinical Trials Unit (CCTU)",
        "Short": "Caner Clin Trials Unit (CCTU)",
        "Subject": '',
    },
    {
        "Code": "219",
        "Long": "Nuclear Magnetic Resonance",
        "Short": "NMR",
        "Subject": '',
    },
    {
        "Code": "222",
        "Long": "School of History and Cultures",
        "Short": "History and Cultures",
        "Subject": 'HIST',
    },
    {
        "Code": "224",
        "Long": "Academic Services",
        "Short": "Academic Services",
        "Subject": '',
    },
    {
        "Code": "225",
        "Long": "History",
        "Short": "History",
        "Subject": 'HIST',
    },
    {
        "Code": "227",
        "Long": "Modern Languages",
        "Short": "Modern Languages",
        "Subject": 'LANG',
    },
    {
        "Code": "228",
        "Long": "Teacher Education",
        "Short": "Teacher Education",
        "Subject": 'TEAC',
    },
    {
        "Code": "229",
        "Long": "Education and Social Justice",
        "Short": "Education & Social Justice",
        "Subject": 'EDUC',
    },
    {
        "Code": "231",
        "Long": "Disability, Inclusion and Special Needs",
        "Short": "Disab, Inclusion & Spec Needs",
        "Subject": 'EDUC',
    },
    {
        "Code": "233",
        "Long": "Graduate School",
        "Short": "Graduate School",
        "Subject": '',
    },
    {
        "Code": "235",
        "Long": "Golf Studies",
        "Short": "Golf Studies",
        "Subject": 'SPEX',
    },
    {
        "Code": "236",
        "Long": "English Literature",
        "Short": "English Literature",
        "Subject": 'ENGL',
    },
    {
        "Code": "237",
        "Long": "English Language and Linguistics",
        "Short": "Eng Lang and Linguistics",
        "Subject": 'ENGL',
    },
    {
        "Code": "237",
        "Long": "Linguistics and Communication",
        "Short": "Linguistics and Communication",
        "Subject": 'ENGL',
    },
    {
        "Code": "238",
        "Long": "Liberal Arts",
        "Short": "Liberal Arts & Natural Science",
        "Subject": 'LIBA',
    },
    {
        "Code": "239",
        "Long": "Classics, Ancient History and Archaeology",
        "Short": "Classics, AH and Archaeology",
        "Subject": 'HIST',
    },
    {
        "Code": "240",
        "Long": "Centre for Byzantine, Ottoman and Modern Greek Studies",
        "Short": "Byzantine, Ottoman, Greek Stud",
        "Subject": 'HIST',
    },
    {
        "Code": "241",
        "Long": "Physiotherapy",
        "Short": "Physiotherapy",
        "Subject": 'PSTY',
    },
    {
        "Code": "242",
        "Long": "Dental Hygiene and Therapy",
        "Short": "Dental Hygiene and Therapy",
        "Subject": 'DENT',
    },
    {
        "Code": "243",
        "Long": "Film and Creative Writing",
        "Short": "Film and Creative Writing",
        "Subject": 'ENGL',
    },
    {
        "Code": "244",
        "Long": "Institute of Forest Research",
        "Short": "Institute of Forest Research",
        "Subject": '',
    },
    {
        "Code": "246",
        "Long": "Accounting",
        "Short": "Accounting",
        "Subject": 'ACCT',
    },
    {
        "Code": "247",
        "Long": "Finance",
        "Short": "Finance",
        "Subject": 'FINC',
    },
    {
        "Code": "252",
        "Long": "Strategy and International Business",
        "Short": "Strategy and Int Business",
        "Subject": 'BUSI',
    },
    {
        "Code": "253",
        "Long": "International Summer School",
        "Short": "International Summer School",
        "Subject": '',
    },
    {
        "Code": "254",
        "Long": "Educational Enterprise",
        "Short": "Educational Enterprise",
        "Subject": '',
    },
    {
        "Code": "255",
        "Long": "Wiley",
        "Short": "Wiley",
        "Subject": '',
    },
    {
        "Code": "256",
        "Long": "Institute of Clinical Sciences",
        "Short": "Institute of Clinical Sciences",
        "Subject": '',
    },
    {
        "Code": "257",
        "Long": "Institute of Metabolism and Systems Research",
        "Short": "Inst of Metabolism and Sys Res",
        "Subject": '',
    },
    {
        "Code": "257",
        "Long": "Department of Metabolism and Systems Science",
        "Short": "Inst of Metabolism and Sys Res",
        "Subject": '',
    },
    {
        "Code": "258",
        "Long": "Institute of Inflammation and Ageing",
        "Short": "Inst of Inflammation / Ageing",
        "Subject": '',
    },
    {
        "Code": "259",
        "Long": "Institute of Microbiology and Infection",
        "Short": "Inst of Microb and Infection",
        "Subject": '',
    },
    {
        "Code": "259",
        "Long": "Microbes, Infection and Microbiomes",
        "Short": "Microbes, Infections, Microbms",
        "Subject": '',
    },
    {
        "Code": "260",
        "Long": "School of Engineering",
        "Short": "Engineering",
        "Subject": 'ENGR',
    },
    {
        "Code": "261",
        "Long": "Management",
        "Short": "Management",
        "Subject": 'MNGT',
    },
    {
        "Code": "262",
        "Long": "Social Policy, Sociology and Criminology",
        "Short": "Soc Policy, Sociology & Crimin",
        "Subject": '',
    },
    {
        "Code": "262",
        "Long": "Social Policy, Sociology and Criminology",
        "Short": "Soc Policy, Sociology & Criminology",
        "Subject": '',
    },
    {
        "Code": "263",
        "Long": "Social Work and Social Care",
        "Short": "Social Work & Social Care",
        "Subject": 'SWSC',
    },
    {
        "Code": "264",
        "Long": "CAL Professional Services",
        "Short": "CAL Professional Services",
        "Subject": '',
    },
    {
        "Code": "265",
        "Long": "University Music",
        "Short": "University Music",
        "Subject": '',
    },
    {
        "Code": "266",
        "Long": "Institute of Translational Medicine",
        "Short": "Inst of Translational Medicine",
        "Subject": '',
    },
    {
        "Code": "267",
        "Long": "Birmingham Health Partners",
        "Short": "Birmingham Health Partners",
        "Subject": '',
    },
    {
        "Code": "268",
        "Long": "Advanced Therapies Facility",
        "Short": "Advanced Therapies Facility",
        "Subject": '',
    },
    {
        "Code": "269",
        "Long": "Life Sciences Campus",
        "Short": "Life Sciences Campus",
        "Subject": '',
    },
    {
        "Code": "270",
        "Long": "Clinical Immunology Service",
        "Short": "Clinical Immunology Service",
        "Subject": '',
    },
    {
        "Code": "271",
        "Long": "High Temperature Research Centre",
        "Short": "High Temperature Research Cent",
        "Subject": '',
    },
    {
        "Code": "272",
        "Long": "Higher Education Futures Institute",
        "Short": "HEFi",
        "Subject": '',
    },
    {
        "Code": "273",
        "Long": "City_REDI",
        "Short": "City-REDI",
        "Subject": '',
    },
    {
        "Code": "274",
        "Long": "Urdang Academy",
        "Short": "Urdang Academy",
        "Subject": '',
    },
    {
        "Code": "275",
        "Long": "Birmingham Leadership Institute",
        "Short": "Birmingham Leadership Inst",
        "Subject": '',
    }
]


module.exports = deptMapping;
