const schoolMapping = [
    {
        "Code": "012",
        "School": "Birmingham Business School",
        "School2": "Birmingham Business School",
        "College": "12",
    },
    {
        "Code": "068",
        "School": "Birmingham International Academy",
        "School2": "Academic Services",
        "College": "15",
    },
    {
        "Code": "027",
        "School": "Birmingham Law School",
        "School2": "Birmingham Law School",
        "College": "11",
    },
    {
        "Code": "074",
        "School": "Birmingham Medical School",
        "School2": "Institute of Clinical Sciences",
        "College": "14",
    },
    {
        "Code": "068",
        "School": "Careers Network",
        "School2": "Academic Services",
        "College": "15",
    },
    {
        "Code": "082",
        "School": "Higher Education Futures institute",
        "School2": "HEFI",
        "College": "15",
    },
    {
        "Code": "023",
        "School": "Institute of Applied Health Research",
        "School2": "Inst of Applied Health Res",
        "College": "14",
    },
    {
        "Code": "065",
        "School": "Institute of Cancer and Genomic Sciences",
        "School2": "Cancer Studies",
        "College": "14",
    },
    {
        "Code": "076",
        "School": "Institute of Cardiovascular Sciences",
        "School2": "Inst of Cardiovascular Science",
        "College": "14",
    },
    {
        "Code": "067",
        "School": "Institute of Immunology and Immunotherapy",
        "School2": "Inst of Immunol + Immunoth",
        "College": "14",
    },
    {
        "Code": "077",
        "School": "Institute of Inflammation and Ageing",
        "School2": "Inst of Inflammation / Ageing",
        "College": "14",
    },
    {
        "Code": "075",
        "School": "Institute of Metabolism and Systems Research",
        "School2": "Inst of Metab / Systems Res",
        "College": "14",
    },
    {
        "Code": "078",
        "School": "Institute of Microbiology and Infection",
        "School2": "Inst Microbiology / Infection",
        "College": "14",
    },
    {
        "Code": "072",
        "School": "Liberal Arts and Natural Sciences",
        "School2": "Liberal Arts & Natural Science",
        "College": "15",
    },
    {
        "Code": "074",
        "School": "School of Biomedical Sciences",
        "School2": "Institute of Clinical Sciences",
        "College": "14",
    },
    {
        "Code": "038",
        "School": "School of Biosciences",
        "School2": "School of Bioscience",
        "College": "10",
    },
    {
        "Code": "056",
        "School": "School of Chemical Engineering",
        "School2": "Chemical Engineering",
        "College": "13",
    },
    {
        "Code": "014",
        "School": "School of Chemistry",
        "School2": "Chemistry",
        "College": "13",
    },
    {
        "Code": "016",
        "School": "School of Computer Science",
        "School2": "Computer Science",
        "College": "13",
    },
    {
        "Code": "074",
        "School": "School of Dentistry",
        "School2": "Institute of Clinical Sciences",
        "College": "14",
    },
    {
        "Code": "020",
        "School": "School of Education",
        "School2": "School of Education",
        "College": "12",
    },
    {
        "Code": "080",
        "School": "School of Engineering",
        "School2": "School of Engineering",
        "College": "13",
    },
    {
        "Code": "046",
        "School": "School of English, Drama And Creative Studies",
        "School2": "Eng, Drama, & Creative Studies",
        "College": "11",
    },
    {
        "Code": "022",
        "School": "School of Geography, Earth and Environmental Sciences",
        "School2": "School of Geog Earth & Env Sci",
        "College": "10",
    },
    {
        "Code": "053",
        "School": "School of Government",
        "School2": "Government",
        "College": "12",
    },
    {
        "Code": "047",
        "School": "School of History and Cultures",
        "School2": "History and Cultures",
        "College": "11",
    },
    {
        "Code": "049",
        "School": "School of Languages, Cultures, Art History and Music",
        "School2": "Lan, Cult, Art Hist & Music",
        "College": "11",
    },
    {
        "Code": "029",
        "School": "School of Mathematics",
        "School2": "Mathematics",
        "College": "13",
    },
    {
        "Code": "058",
        "School": "School of Metallurgy and Materials",
        "School2": "Metallurgy and Materials",
        "College": "13",
    },
    {
        "Code": "074",
        "School": "School of Nursing",
        "School2": "Institute of Clinical Sciences",
        "College": "14",
    },
    {
        "Code": "074",
        "School": "School of Pharmacy",
        "School2": "Institute of Clinical Sciences",
        "College": "14",
    },
    {
        "Code": "050",
        "School": "School of Philosophy, Theology and Religion",
        "School2": "Phil, Theology and Religion",
        "College": "11",
    },
    {
        "Code": "032",
        "School": "School of Physics and Astronomy",
        "School2": "Physics and Astronomy",
        "College": "13",
    },
    {
        "Code": "033",
        "School": "School of Psychology",
        "School2": "School of Psychology",
        "College": "10",
    },
    {
        "Code": "035",
        "School": "School of Social Policy",
        "School2": "School of Social Policy",
        "College": "12",
    },
    {
        "Code": "036",
        "School": "School of Sport, Exercise and Rehabilitation Sciences",
        "School2": "Sport, Ex and Rehab Sciences",
        "College": "10",
    },
    {
        "Code": "068",
        "School": "University Graduate School",
        "School2": "Academic Services",
        "College": "15",
    }
]

module.exports = schoolMapping;